spring:
  application:
    name: notification-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:notif_user}
    password: ${SPRING_DATASOURCE_PASSWORD:notif_pass}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

