spring:
  application:
    name: ecommerce-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
    username: ${SPRING_DATASOURCE_USERNAME:ecom_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ecom_pass}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

jwt:
  secret: ${JWT_SECRET:localtestkeydopemysupersecretkey123456}
  expiration: ${JWT_EXPIRATION:3600000}